"""
Django settings for feriavirtual2 project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&@6ghnnsg2^&$ddsq2i4=sk=q7(2p#dl@$8hq5*jg#_v1xu3p$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'feriavirtualapp.apps.FeriavirtualappConfig',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'feriavirtual2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'feriavirtualapp.context_processor.cart_total_amount',
            ],
        },
    },
]

WSGI_APPLICATION = 'feriavirtual2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': "sql_server.pyodbc",
'HOST': "54.145.168.187\EC2AMAZ-BDN65VE\SQLEXPRESS01,14334",
'USER': "sa",
'PASSWORD': "Pvsa**2021",
'NAME': "maipo-grande",
'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server", 
'host_is_server': True
},
}
}



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
AUTH_USER_MODEL = 'feriavirtualapp.User'
LOGIN_REDIRECT_URL = 'seguimientoLista'

#EMAIL BACKEND
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'servidorgenerico2020@gmail.com'
EMAIL_HOST_PASSWORD = 'myppdduuhvoxeiob'

# WEBPAY
WEBPAY_RETURN_IP_ADDRESS = '127.0.0.1'  # Ip address of the host hosting the e-commerce site.
WEBPAY_RETURN_PORT = 8000  # Port where the server is listening for

WEBPAY_NORMAL = {

    'ACTIVE_ENVIRON': 'INTEGRATION',  # INTEGRATION, PRODUCTION or CERTIFICATION
    # This values determines which url is used
    # from the 'ENVIRONMENTS' setting.

    'ENVIRONMENTS': {  # Map the service urls to the active environment value.
        'INTEGRATION': 'https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl',
    },

    # The following settings are self explanatory.
    'PRIVATE_KEY': '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C',
    'COMMERCE_CODE': '597055555532'
}

PWA_APP_NAME= "FeriaMaipoGrande!"
PWA_APP_DESCRIPTION = "Pagina Maipo Grande"
PWA_APP_THEME_COLOR = "#02e3f79e"
PWA_APP_BACKGROUND_COLOR = "#02e3f79e"

PWA_APP_ICONS = [
    {
        "src": "/static/img/maipologo.png",
        "sizes": "160x160"
    }
]

PWA_APP_ICONS_APPLE = [
    {
       "src": "/static/img/maipologo.png",
        "sizes": "160x160"
    }
]